version: '3'
services:
  soketi:
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    environment:
      SOKETI_DEBUG: 0
      SOKETI_METRICS_SERVER_PORT: 9601
      SOKETI_DEFAULT_APP_ID: your-app-id
      SOKETI_DEFAULT_APP_KEY: your-app-key
      SOKETI_DEFAULT_APP_SECRET: your-app-secret
    ports:
      - '6001:6001'
      - '9601:9601'
    networks:
      - soketi-network

networks:
  soketi-network:
    driver: bridge
